stock-api:
  key:
    name: ${API_KEY_NAME}
    value: ${API_KEY_VALUE}
  address: ${API_ADDRESS}
  main-endpoint: ${API_MAIN-ENDPOINT}

general:
  stocks: ${STOCKS}
  timeout: ${TIMEOUT}
  wakeup-url: ${WAKEUP_URL}
spring:
  main:
    allow-bean-definition-overriding: true